language: node_js
node_js:
  - '12.13.0'
cache: yarn

install:
  - yarn global add lerna jest
  - lerna bootstrap
matrix:
  include:
    - name: 'Blog Pipeline'
      env: PACKAGE_LOCATION=packages/blog
    - name: 'Shop Pipeline'
      env: PACKAGE_LOCATION=packages/shop
script:
  - cd $PACKAGE_LOCATION
  - yarn test
  - yarn build
